language: python

branches:
  except:
    - gh-pages

python:
  - "2.6"
  - "2.7"

install:
  - python setup.py install
  - ./scripts/travis-install.sh

script:
  - ./scripts/travis-run.sh

env:
  matrix:
    - REPO_URL=https://github.com/ckan/ckan REPO_BRANCH=master
    - REPO_URL=https://github.com/ckan/ckan REPO_BRANCH=ckan-2.2
    - REPO_URL=https://github.com/ckan/ckan REPO_BRANCH=ckan-2.1

matrix:
  allow_failures:
    ## Ckan 2.1 is very buggy -- expecting failures there..
    - env: REPO_URL=https://github.com/ckan/ckan REPO_BRANCH=ckan-2.1
