#!/bin/bash

## Script to run tests for Ckan API client

set -e  # Fail fast
HERE="$( readlink -f $( dirname "$BASH_SOURCE" ) )"
CKAN_ENVS_DIR="$( readlink -f "${HERE}/../.ckan-envs/" )"
LOCAL_SETTINGS_FILE="$( readlink -f "${HERE}/.local-settings/" )"

## ----- Default Configuration -------------------------------
REPO_URL=https://github.com/ckan/ckan
REPO_BRANCH=master
PYTHON=/usr/bin/python2.7
CKAN_POSTGRES_ADMIN=postgresql://postgres:postgrespass@database.local/
CKAN_SOLR=http://database.local:8983/solr/ckan-2.0
CKAN_VIRTUALENV="${CKAN_ENVS_DIR}/ckan-master"
##------------------------------------------------------------

if [ -e "$LOCAL_SETTINGS_FILE" ]; then
    source "$LOCAL_SETTINGS_FILE"
fi

## --- Create virtualenv if it doesn't exist
if [ ! -e "${CKAN_VIRTUALENV}" ]; then
    ORIG_DIR="$( pwd )"

    mkdir -p "$CKAN_VIRTUALENV"

    ## Install ckan there
    echo "Creating virtualenv using $( "$PYTHON" --version ) from ${PYTHON}"
    virtualenv -p "$PYTHON" "$CKAN_VIRTUALENV"

    ## Clone repository
    echo "Installing ckan from ${REPO_URL} (branch: ${REPO_BRANCH})"
    mkdir -p "${CKAN_VIRTUALENV}/src"
    git clone "$REPO_URL" -b "$REPO_BRANCH" --depth=1 "${CKAN_VIRTUALENV}/src/ckan"

    ## Install ckan
    cd "${CKAN_VIRTUALENV}/src/ckan"
    "${CKAN_VIRTUALENV}"/bin/pip install -r ./requirements.txt
    "${CKAN_VIRTUALENV}"/bin/python setup.py install

    ## Copy configuration file
    mkdir -p "${CKAN_VIRTUALENV}/etc/ckan"
    cp "${CKAN_VIRTUALENV}/src/ckan/ckan/config/who.ini" "${CKAN_VIRTUALENV}/etc/ckan/who.ini"
    # Ckan configuration files will be generated by fixtures

    cd "$ORIG_DIR"
fi

## --- Export environment
export CKAN_VIRTUALENV
export CKAN_POSTGRES_ADMIN
export CKAN_SOLR

## --- Launch tests
# exec py.test -vvv -rsxX ckan_api_client/tests "$@"

# exec py.test -vvv -rsxX --pep8 \
#      --cov-report=term-missing --cov=ckan_api_client \
#      ckan_api_client/tests "$@"

PYTEST_ARGS="-vvv -rsxX"
PYTEST_ARGS+=" --pep8"
PYTEST_ARGS+=" --cov-report=term-missing --cov=ckan_api_client"

if [ -z "$1" ]; then
    PYTEST_ARGS+=" ckan_api_client/tests"
fi

exec py.test $PYTEST_ARGS "$@"
